  steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest','--no-cache', '.']
  logsBucket: 'gs:// terraform-project-443816-cloudbuild-logs'
  options:
      logging: GCS_ONLY

  # Step 2: Push the image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest']
  

  # Step 3: Create the Cloud Run Job
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'jobs','deploy', '${_JOB_NAME}', '--image',
       'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest',
      '--region', 'europe-west1',
       '--args', 'dbt run , dbt docs generate', '--set-env-vars', 'DBT_DOCS_BUCKET=${_DBT_DOCS_BUCKET}']
# Deploy Cloud scheduler job

#images:
  #- 'gcr.io/terraform-project-443816/dbt-cloud-run:latest'

  substitutions:
    _IMAGE_NAME: 'dbt-cloud-run-test'
    _JOB_NAME: 'dbt-cloud-run-job'
    _DBT_DOCS_BUCKET: 'terraform-project-443816_cloudbuild'

